### ISSUE TITLE
fss results: I s there instability?

### ISSUE THREAD

**Issue by timm** [ai-se/Birch_Bellwether#22]

**Comment by Suvodeep90** [comment]
Self FSS
![FSS_ALL](https://user-images.githubusercontent.com/31140098/63866839-e0bda580-c981-11e9-95e1-0611e69c0256.png)

Bellwether FSS
![FSS_level0](https://user-images.githubusercontent.com/31140098/63866851-e4e9c300-c981-11e9-91ed-e92dd324622c.png)
