### ISSUE TITLE
2.3 problems with transfer learning

### ISSUE THREAD

**Issue by timm** [ai-se/Birch_Bellwether#4]
complexity and cost.

 As to the problem of running a   learner (say) 27 million times,
 we are often asked if that can be solved, just by   buying more cloud-based CPU.
 In reply, we say that CPUs are not an unlimited resource that should be
applied unquestionably to computationally expensive problems.
We can no longer rely on Moore's
Law~\cite{658762} to double our computational power
very 18 months since
power consumption and heat
dissipation issues now block further
exponential increases~\cite{kuman03}.  
Even if we could build
those faster CPUs, we would still need to power them.
The
pollution associated with 
powering the cloud is now a significant issue.
Data centers consume 1.5\% of globally electrical
output and this value is predicted to grow~\cite{koomey08}. Data centers in the
USA used 91 billion kilowatt-hours of electrical
energy in 2013, and they will be using 139 billion
kilowatt-hours by 2020~\cite{thib14}.
And even if (a)~we could
build faster CPUs and even if (b) we had the energy to
power them and even if (c) we could dispose of the
pollution associated with generating that energy,
then all that CPU+energy+pollution offset would be a service
that must be paid for. Fisher et al. \cite{Fisher:2012}
comment that cloud
computation is a heavily monetized environment that charges for all
their services (storage, uploads, downloads, and CPU time).
While each small part of that service is cheap, the total annual
cost to an organization can be exorbitant.
Google reports that a 1\%
reduction in CPU requirements saves them millions of dollars in power costs.

**Comment by timm** [comment]
@ARTICLE{658762, 
author={G. E. Moore}, 
journal={Proceedings of the IEEE}, 
title={Cramming More Components Onto Integrated Circuits}, 
year={1998}, 
volume={86}, 
number={1}, 
pages={82-85}, 
keywords={Aerospace electronics;Costs;Home computing;Integrated circuit reliability;Integrated circuit technology;Portable computers;Semiconductor films;Space technology;Switches;Telephony}, 
doi={10.1109/JPROC.1998.658762}, 
ISSN={0018-9219}, 
month={Jan},}

**Comment by rahlk** [comment]
@rahlk paste that cost picture

**Comment by timm** [comment]
@article {koomey08,
	title = {Report to Congress on Server and Data Center Energy Efficiency: Public Law 109-431},
	year = {2008},
	month = {06/2008},
	address = {Berkeley, CA},
	keywords = {combined heat and power, computers, data centers, energy forecasting, energy star, information technology, servers},
	attachments = {https://eetd.lbl.gov/sites/all/files/pdf_4.pdf},
	author = {Richard E. Brown and Eric R. Masanet and Bruce Nordman and William F. Tschudi and Arman Shehabi and John Stanley and Jonathan G. Koomey and Dale A. Sartor and Peter T. Chan}
}

**Comment by timm** [comment]
@misc{thib14,
   author="Patrick Thibodeau",
   title="Data centers are the new polluters, August 26",
   year=2014,
   note="Available from http://v.gd/TpSdZn."
   }

**Comment by timm** [comment]
@article{Fisher:2012,
 author = {Fisher, Danyel and DeLine, Rob and Czerwinski, Mary and Drucker, Steven},
 title = {Interactions with Big Data Analytics},
 journal = {interactions},
 issue_date = {May + June 2012},
 volume = {19},
 number = {3},
 month = may,
 year = {2012},
 issn = {1072-5520},
 pages = {50--59},
 numpages = {10},
 url = {http://doi.acm.org/10.1145/2168931.2168943},
 doi = {10.1145/2168931.2168943},
 acmid = {2168943},
 publisher = {ACM},
 address = {New York, NY, USA},
}
