### ISSUE TITLE
cool figure on cost

### ISSUE THREAD

**Issue by timm** [ai-se/Birch_Bellwether#8]
![image](https://user-images.githubusercontent.com/29195/63195936-f6f26a00-c041-11e9-9c7f-f6ebcd61fb69.png)

**Comment by timm** [comment]
make the number BIGGER

- repeat for 10x10 way
- repeat for M data sets
- repeat X times for debugging

**Comment by Suvodeep90** [comment]
https://docs.google.com/spreadsheets/d/1FFLCE2W4MOT6RT44meLBd6FGaEQI01YJXmOMDiHPzz0/edit#gid=1331919034

![cost($) and cost($)-2](https://user-images.githubusercontent.com/31140098/63212274-d7a21e00-c0cf-11e9-8b4e-455b1f117eae.png)

```
projecs | Bell0 cost($) | BUBBLE cost($)
-- | -- | --
100 | 0.02 | 0.00
200 | 0.06 | 0.01
400 | 0.25 | 0.01
800 | 1.02 | 0.03
1600 | 4.06 | 0.05
3200 | 16.25 | 0.10
6400 | 64.99 | 0.20
12800 | 259.96 | 0.41
25600 | 1039.84 | 0.81
51200 | 4159.35 | 1.62
102400 | 16637.41 | 3.25
204800 | 66549.62 | 6.50
409600 | 266198.49 | 13.00
819200 | 1064793.98 | 26.00
1638400 | 4259175.90 | 51.99
3276800 | 17036703.61 | 103.98
6553600 | 68146814.43 | 207.97
13107200 | 272587257.72 | 415.94
26214400 | 1090349030.88 | 831.87
```
